name: '${name}'
version: '${version}'
main: fr.traqueur.storageplus.ZStoragePlus
api-version: '1.21'
depend:
  - zMenu
softdepend: [PlaceholderAPI]

libraries:
  - 'dev.dejvokep:boosted-yaml:1.3.6'
  - 'net.kyori:adventure-api:4.17.0'
  - 'net.kyori:adventure-text-minimessage:4.17.0'
  - 'net.kyori:adventure-platform-bukkit:4.3.4'
